In [3]:
from sklearn import datasets

In [4]:
from sklearn.neighbors import KNeighborsClassifier

In [5]:
from sklearn.metrics import roc_curve

In [6]:
import matplotlib.pyplot as plt

In [7]:
from sklearn.model_selection import train_test_split
from sklearn import utils

In [8]:
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix

In [9]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn import preprocessing

In [10]:
dataset=pd.read_csv("Two_points_KNN.csv")

In [36]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,2].values

In [37]:
x

array([[ -2.54345625, -10.81635752],
       [  9.43446606,  -2.57200001],
       [  3.36864566, -10.19467054],
       ...,
       [ -1.3935983 ,  -7.876754  ],
       [ -7.70897181,  -4.29800246],
       [  4.6107791 ,  10.62947734]])

In [38]:
y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [39]:
dataset.head()

x          y  Unnamed: 2
0 -2.543456 -10.816358           0
1  9.434466  -2.572000           0
2  3.368646 -10.194671           0
3  1.341407  -4.204140           0
4  9.547758  -2.220580           0

In [40]:
x_train, x_test, y_train, y_test = train_test_split(x, y)

In [41]:
knn=KNeighborsClassifier()

In [42]:
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [43]:
predictions=knn.predict(x_test)

In [51]:
confusion_matrix(y_test,predictions)

array([[258,   0],
       [  0, 242]], dtype=int64)

In [52]:
knn.score(x_test,y_test)

1.0

In [53]:
precision_score(y_test,predictions)

1.0

In [54]:
recall_score(y_test, predictions)

1.0

In [55]:
f1_score(y_test, predictions)

1.0